language: java
# Disable advanced operation: this operation does not required elevated rights
#sudo: false
jdk:
  #- oraclejdk8
  - oraclejdk11
  - openjdk11


################
# CODACITY INTEGRATION (static code analysis)
# Requirement: configure TRAVIS build and add the codacity token as environment variable
#              export CODACY_PROJECT_TOKEN=%Project_Token%
#####################################


# cache the build tool's caches
cache:
  directories:
    - $HOME/.m2
    - $HOME/.gradle

# First of all, remove all previous build of current project
before_cache:
  - rm -rf $HOME/.m2/repository/eu/daxiongmao

# Download codacity artifact
before_install:
  - sudo apt-get install jq
  - bash <(wget -q -O - https://coverage.codacy.com/get.sh)
  - ls -l


# Override default install with settings
install:
  - mvn --settings .travis/settings.xml install -DskipTests=true -Dgpg.skip -Dmaven.javadoc.skip=true -B -V

# Send quality report
after_success:
  - echo "Listing jacoco files"
  - find . -name jacoco.xml
  - echo "Listing all target jacoco"
  - ls -l */**/target/jacoco
  - ./codacy-coverage-reporter report -l Java -r backend/target/jacoco/jacoco.xml
