language: java
# Do not run sudoer operations (faster build)
sudo: false
jdk:
  #- oraclejdk8
  - oraclejdk11
  - openjdk11


####################################################################
# Travis environment variables required for static code analysis
####################################################################
# CODACY (https://codacy.com)
#        export CODACY_PROJECT_TOKEN=%Project_Token%
# CODECOV (https://codecov.io)
#        export CODECOV_TOKEN=%repository_token%
####################################################################


# cache the build tool's caches
cache:
  directories:
    - $HOME/.m2
    - $HOME/.gradle

# First of all, remove all previous build of current project
before_cache:
  - rm -rf $HOME/.m2/repository/eu/daxiongmao

# Override default install with settings
install:
  - mvn clean install -DskipTests=true -Dmaven.javadoc.skip=true -B -V

# Send quality reports
after_success:
  # http://codecov.io
  - bash <(curl -s https://codecov.io/bash)
  # http://codacy.com
  - bash <(curl -Ls https://coverage.codacy.com/get.sh)
  #- bash <(curl -Ls https://coverage.codacy.com/get.sh) report -l Java -r backend/target/jacoco/jacoco.xml --partial
  #- bash <(curl -Ls https://coverage.codacy.com/get.sh) final
